version: "3.1"

services:
  webserver:
    image: altimofeev/webserver-localhost
    container_name: webserver
    working_dir: ${WORKDIR}
    ports:
      - ${APP_PORT}:80
    depends_on:
      - app
    volumes:
      - .:${WORKDIR}
      - sock_test:${SOCKET_DIR}

  app:
    image: altimofeev/php-fpm
    container_name: app
    env_file:
      - .env
    working_dir: ${WORKDIR}
    volumes:
      - .:${WORKDIR}
      - sock_test:${SOCKET_DIR}

volumes:
  sock_test:
